"""init

Revision ID: e32a3a0cab52
Revises:
Create Date: 2026-02-03 19:46:30.390809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e32a3a0cab52"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creature",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mythology", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("creature_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("danger_level", sa.Integer(), nullable=False),
        sa.Column("habitat", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_modify", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_creature_name"), "creature", ["name"], unique=True)
    op.create_table(
        "creatureclass",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("border_color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_creatureclass_name"), "creatureclass", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_creatureclass_name"), table_name="creatureclass")
    op.drop_table("creatureclass")
    op.drop_index(op.f("ix_creature_name"), table_name="creature")
    op.drop_table("creature")
    # ### end Alembic commands ###
